Test:
  ==: SBEBlockValueData
  blockValues:
    ==: SBEBlockValueCollection
    DIRT:
      ==: SBEBlockValuation
      maximumPool: default
      postPoolValue: 0
      value: 1
      poolChange: 1
    defaultBlockValuation:
      ==: SBEBlockValuation
      maximumPool: default
      postPoolValue: 0
      value: 1
      poolChange: 1
  maximumPools:
    ==: SBEMaximumPoolCollection
    default:
      ==: SBEMaximumPool
      max: -1
    test:
      ==: SBEMaximumPool
      max: 200