#Contains various block values.  This can be set to whatever is wanted.
#It is only used when useCustomBlockValues is set to true in config.yml.

#Default value of a block.
defaultBlockValue: 1

#Pools of maximums
maximumPools: 
  cobbleCount: 
    max: 10000

#Actual values
blockValues:
  #Air 
  0: 0
  #Water and lava, flowing and nonflowing
  8: 0
  9: 0
  10: 0
  11: 0
  #Cobble
  4: 
    value: 1
    maximumPool: 'cobbleCount'
  #Diamond block
  57: 300
  #Gold block, enchantment table, Dragon egg (!)
  41: 150
  116: 150
  122: 150
  #Iron block, Obsidian: 
  42: 10
  49: 10
  #Bookshelf, jukebox 
  47: 5
  84: 5
  #Ice, clay, nether brick, grass, mycelium (mycel? wat bukkit)
  79: 3
  82: 3
  112: 3
  2: 3
  110: 3
  #Stone brick (smooth brick?), brick, wool, sandstone, end stone, 
  #brick stairs, stone stairs, double stone-based slabs, glass
  98: 2
  45: 2
  35: 2
  24: 2
  121: 2
  108: 2
  109: 2
  43: 2
  20: 2