Test:
  ==: SBEBlockValueMapping
  blockValues:
    ==: SBEBlockValueCollection
    DIRT:
      ==: SBEBlockValuation
      defualt:
        ==: BlockValueData
        maximumPool: default
        postPoolValue: 0
        value: 1
        poolChange: 1
      '4':
        ==: BlockValueData
        maximumPool: default
        postPoolValue: 0
        value: 1
        poolChange: 1
    defaultBlockValuation:
      ==: SBEBlockValuation
      defualt:
        ==: BlockValueData
        maximumPool: default
        postPoolValue: 0
        value: 1
        poolChange: 1
      '4':
        ==: BlockValueData
        maximumPool: default
        postPoolValue: 0
        value: 1
        poolChange: 1
  maximumPools:
    ==: SBEMaximumPoolCollection
    default:
      ==: SBEMaximumPool
      max: -1
    test:
      ==: SBEMaximumPool
      max: 200
