#Default config.yml

uSkyBlockOverrides:
  islandCommand:
    #Alternative help system, which should make things nicer.
    enableHelp2: true
    #Fixes uSkyBlock not accepting case-mixed commands.  But, it does
    #this by bringing the command to lowercase.  This shouldn't cause
    #issues, but it is possible for a case-sensitive command to be added.
    #As of right now that isn't an issue, but this should be disabled only
    #if it becomes an issue.
    allowIgnoreCase: true
    #Use custom block values?  (See block_values.yml)
    useCustomBlockValues: true

sendHome: 
  #Controls whether or not members can send players back to their island.
  #If false, only owners can do so.
  allowMembersToSendHome: true
  #Controls whether /spawn is used to send players to spawn.
  #If false, uSkyBlock's skyWorld's spawn is used.
  #Set this to false if /spawn is not avaiable to all players.
  useSpawnCommandForSpawn: true

errorHandling: 
  #Broadcast an error to all players who have the permission 
  #sbe.debug.crashes.broadcast set - This includes ops by default.
  #Disabling this means that no receive this information.
  #There is potential for errors to ignore this, for very important errors.
  broadcastOnError: true
  #Similar to above, but only for logins.  The permission is 
  notifyOfExistingOnLogin: true
  
#The warning that is shown when someone places a wither skull, to remind
#them of the true height of a wither - 4 blocks tall.
witherWarning: 
  #Enable/disable.
  enabled: true
  #The main message (displayed first)
  warningText: "&fHey!  Be careful!  While the model to make a wither is 3 by 3, the actual wither is 1 by 4!  If you're trying to cage it, it's possible for it to escape unless your cage is 4 high!"
  #The text that describes how to opt out (displayed next)
  optOutText: "&7&oTo disable this message, do '&r&7/pokechu22 WitherWarning off&7&o'."