#Default config.yml

errorHandling: 
  #Broadcast an error to all players who have the permission 
  #sbe.debug.crashes.broadcast set - This includes ops by default.
  #Disabling this means that no receive this information.
  #There is potential for errors to ignore this, for very important errors.
  broadcastOnError: true
  #Similar to above, but only for logins.  The permission is 
  notifyOfExistingOnLogin: true
  
#The warning that is shown when someone places a wither skull, to remind
#them of the true height of a wither - 4 blocks tall.
witherWarning: 
  #Enable/disable.
  enabled: true
  #The main message (displayed first)
  warningText: "&fHey!  Be careful!  While the model to make a wither is 3 by 3, the actual wither is 1 by 4!  If you're trying to cage it, it's possible for it to escape unless your cage is 4 high!"
  #The text that describes how to opt out (displayed next)
  optOutText: "&7&oTo disable this message, do '&r&7/pokechu22 WitherWarning off&7&o'."

#Multichallenge functionality.
multiChallenge: 
  tax: 1
  #The way to round the tax.  
  #Valid values:
  # * Round up: Lossy
  # * Round up: Keep
  # * Round nearest: Lossy
  # * Round nearest: Keep
  # * Round down: Lossy
  # * Round down: Keep
  roundMode: "Round up: Lossy"

#Allows placement of superstone, since 1.8 removed it.  (When enabled, normal slabs with 
#data values higher than 8 (normally upside down slabs and unobtainable in the inventory) will
#create super stone when placed (but upside down slabs that are that way from a normal slab won't))  
enableSlabOverrides: true

#Enables/disables the protection of various 
enableWorldGaurdEntityProtection: true