#An example of island settings.  Normaly, these are modified in-game, however.

location: "x0z0" #The raw coordinates of the island.
owner: "" #The person who owns the island.  Used only to confirm stuff.
#This is for migrational purposes, if we ever port to use 
#UUIDPlayerInfo from the new version.
ownerUUID: 0 

guests: [] # See beelow for the definition of guest.
geustUUIDs: [] #UUIDS of guests, for porting purposes.

#Levels: Owner, member, guest (!), nonmember.  
#Owner - The owner of the island.
#Member - A invited player, but not the owner.
#Guest - Custom rank - Allows a player to temporarily have special permissions.
#Guest is removed when the owner disconects; only the owner can grant guest.
#Nonmember - Any other player. 

ownerPermissions: 
  canBuildAll: true
  buildAllowedBlocks: [] #Can place only these if canBuildAll is false
  buildBannedBlocks: [] #Can't place these, even if canBuildAll is true
  
  canBreakAll: true
  breakAllowedBlocks: [] #Can break only these if canBreakAll is false
  breakBannedBlocks: [] #Can't break these, even if canBreakAll is true
  
  #Can use anything. The below are more detailed specifiers.
  #If it is false and (eg) canUseChests is true, then the other's value is used.
  #If it is true and (eg) canUseChests, are false, then this's value is used.
  canUseAll: true
  useAllowedBlocks: [] #Can use only these if canBuildAll is false
  useBannedBlocks: [] #Can't use these, even if canBreakAll is true
  canUseChests: true
  canUseFurnaces: true
  canUseAnvils: true
  canUseEnchanters: true
  canUseButtons: true
  canUseLevers: true
  canUseDoors: true
  
  canAttackAllMobs: true
  canAttackAnimals: true
  canAttackHostile: true
  attackAllowedMobs: [] #Can attack only these if canAttackAllMobs is false
  attackBannedMobs: [] #Can't attack these, even if canAttackAllMobs is true
  
  canEat: true
  
  canBreakAllHanging: true #Hangings, such as paintings.
  breakAllowedHangings: []
  breakBannedHangings: []
  
  canUseBeds: true
  
  canPVP: true
  
  canFillBuckets: true
  canEmptyBuckets: true
  
  canShearSheep: true
  
  canUseEntities: true #Leads, opening donkes, ect.
  
  canDamageAllVehicles: true
  damageAllowedVehicles: []
  damageBannedVehicles: []
  
  canEnterAllVehicles: true
  enterAllowedVehicles: []
  enterBannedVehicles: []
  
memberPermissions: 
  canBuildAll: true
  buildAllowedBlocks: [] #Can place only these if canBuildAll is false
  buildBannedBlocks: [] #Can't place these, even if canBuildAll is true
  
  canBreakAll: true
  breakAllowedBlocks: [] #Can break only these if canBreakAll is false
  breakBannedBlocks: [] #Can't break these, even if canBreakAll is true
  
  #Can use anything. The below are more detailed specifiers.
  #If it is false and (eg) canUseChests is true, then the other's value is used.
  #If it is true and (eg) canUseChests, are false, then this's value is used.
  canUseAll: true
  useAllowedBlocks: [] #Can use only these if canBuildAll is false
  useBannedBlocks: [] #Can't use these, even if canBreakAll is true
  canUseChests: true
  canUseFurnaces: true
  canUseAnvils: true
  canUseEnchanters: true
  canUseButtons: true
  canUseLevers: true
  canUseDoors: true
  
  canAttackAllMobs: true
  canAttackAnimals: true
  canAttackHostile: true
  attackAllowedMobs: [] #Can attack only these if canAttackAllMobs is false
  attackBannedMobs: [] #Can't attack these, even if canAttackAllMobs is true
  
  canEat: true
  
  canBreakAllHanging: true #Hangings, such as paintings.
  breakAllowedHangings: []
  breakBannedHangings: []
  
  canUseBeds: true
  
  canPVP: true
  
  canFillBuckets: true
  canEmptyBuckets: true
  
  canShearSheep: true
  
  canUseEntities: true #Leads, opening donkes, ect.
  
  canDamageAllVehicles: true
  damageAllowedVehicles: []
  damageBannedVehicles: []
  
  canEnterAllVehicles: true
  
guestPermissions: 
  canBuildAll: false
  buildAllowedBlocks: [] #Can place only these if canBuildAll is false
  buildBannedBlocks: [] #Can't place these, even if canBuildAll is true
  
  canBreakAll: false
  breakAllowedBlocks: [] #Can break only these if canBreakAll is false
  breakBannedBlocks: [] #Can't break these, even if canBreakAll is true
  
  #Can use anything. The below are more detailed specifiers.
  #If it is false and (eg) canUseChests is true, then the other's value is used.
  #If it is true and (eg) canUseChests, are false, then this's value is used.
  canUseAll: false 
  useAllowedBlocks: [] #Can use only these if canBuildAll is false
  useBannedBlocks: [] #Can't use these, even if canBreakAll is true
  canUseChests: false
  canUseFurnaces: false
  canUseAnvils: false
  canUseEnchanters: false
  canUseButtons: false
  canUseLevers: false
  canUseDoors: false
  
  canAttackAllMobs: false
  canAttackAnimals: false
  canAttackHostile: false
  attackAllowedMobs: [] #Can attack only these if canAttackAllMobs is false
  attackBannedMobs: [] #Can't attack these, even if canAttackAllMobs is true
  
  canEat: true
  
  canBreakAllHanging: false #Hangings, such as paintings.
  breakAllowedHangings: []
  breakBannedHangings: []
  
  canUseBeds: false
  
  canPVP: false
  
  canFillBuckets: false
  canEmptyBuckets: false
  
  canShearSheep: false
  
  canUseEntities: false #Leads, opening donkes, ect.
  
  canDamageAllVehicles: false
  damageAllowedVehicles: []
  damageBannedVehicles: []
  
  canEnterAllVehicles: false
  
nonmemberPermissions:
  canBuildAll: false
  buildAllowedBlocks: [] #Can place only these if canBuildAll is false
  buildBannedBlocks: [] #Can't place these, even if canBuildAll is true
  
  canBreakAll: false
  breakAllowedBlocks: [] #Can break only these if canBreakAll is false
  breakBannedBlocks: [] #Can't break these, even if canBreakAll is true
  
  #Can use anything. The below are more detailed specifiers.
  #If it is false and (eg) canUseChests is true, then the other's value is used.
  #If it is true and (eg) canUseChests, are false, then this's value is used.
  canUseAll: false 
  useAllowedBlocks: [] #Can use only these if canBuildAll is false
  useBannedBlocks: [] #Can't use these, even if canBreakAll is true
  canUseChests: false
  canUseFurnaces: false
  canUseAnvils: false
  canUseEnchanters: false
  canUseButtons: false
  canUseLevers: false
  canUseDoors: false
  
  canAttackAllMobs: false
  canAttackAnimals: false
  canAttackHostile: false
  attackAllowedMobs: [] #Can attack only these if canAttackAllMobs is false
  attackBannedMobs: [] #Can't attack these, even if canAttackAllMobs is true
  
  canEat: true
  
  canBreakAllHanging: false #Hangings, such as paintings.
  breakAllowedHangings: []
  breakBannedHangings: []
  
  canUseBeds: false
  
  canPVP: false
  
  canFillBuckets: false
  canEmptyBuckets: false
  
  canShearSheep: false
  
  canUseEntities: false #Leads, opening donkes, ect.
  
  canDamageAllVehicles: false
  damageAllowedVehicles: []
  damageBannedVehicles: []
  
  canEnterAllVehicles: false